[project]
name = "yasl"
version = "0.1.7"
description = "The YAML Advanced Schema Language (YASL) allow you to define and validate YAML data using complex data structures."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "annotated-types==0.7.0",
    "certifi==2025.8.3",
    "charset-normalizer==3.4.3",
    "colorama==0.4.6",
    "coverage==7.10.6",
    "cucumber-expressions==18.0.1",
    "cucumber-tag-expressions==6.2.0",
    "dnspython==2.8.0",
    "email-validator==2.3.0",
    "idna==3.10",
    "iniconfig==2.1.0",
    "packaging==25.0",
    "parse==1.20.2",
    "parse-type==0.6.6",
    "pluggy==1.6.0",
    "pydantic==2.11.7",
    "pydantic-core==2.33.2",
    "pygments==2.19.2",
    "requests==2.32.5",
    "ruamel-yaml==0.18.15",
    "ruamel-yaml-clib==0.2.12",
    "setuptools>=80.9.0",
    "six==1.17.0",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.1",
    "urllib3==2.5.0",
]

[project.optional-dependencies]
dev = [
    "pytest==8.4.1",
    "pytest-cov==7.0.0",
    "behave==1.3.2",
    "ruff==0.13.0",
    "build==1.3.0",
    "toml==0.10.2",
]

[project.scripts]
yasl = "yasl.cli:main"
