# .github/workflows/behave-tests.yml
name: Behave Acceptance Tests
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-behave-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your desired Python version

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install behave

      - name: Run Behave Tests
        run: |
          cd features
          behave