name: YASL CI

on:
  push:
    branches: [ main, inputs ]
  pull_request:
    branches: [ main, inputs ]

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build Go shared library
        run: |
          go build -buildmode=c-shared -o api/python/yasl.so main.go
          go build -buildmode=c-shared -o api/javascript/yasl.so main.go
      - name: Run Go tests
        run: go test ./...

  test-python:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run Python API tests
        run: |
          cp api/python/yasl.so tests/python/
          python -m unittest discover -s tests/python

  test-javascript:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install ffi-napi
          npm install jest
      - name: Run JavaScript API tests
        run: |
          cp api/javascript/yasl.so tests/javascript/
          npx jest tests/javascript/test_yasl_api.test.js
