# .github/workflows/ci.yml
name: YASL CI/CD

on:
  push:
  pull_request:

jobs:
  build-test-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Setup environment with uv
        run: |
          uv pip install -e .

      - name: Run unit tests
        run: |
          uv run pytest --cov=src --cov-report=xml --cov-fail-under=75 tests/

      - name: Check formatting with ruff
        run: |
          uv run ruff check src/ tests/

      - name: Check CLI tool
        run: |
          uv run yasl --version
          uv run yasl --help

      - name: Build wheel
        run: |
          uv pip install build
          python -m build --wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: yasl-wheel
          path: dist/*.whl

  publish:
    runs-on: ubuntu-latest
    needs: build-test-format
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: yasl-wheel
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
