# .github/workflows/ci.yml
name: YASL CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: yasl
          path: yasl

      - name: Upload Linux shared library
        uses: actions/upload-artifact@v4
        with:
          name: yasl-so
          path: yasl.so

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: yasl.exe
          path: yasl.exe

      - name: Upload Windows shared library
        uses: actions/upload-artifact@v4
        with:
          name: yasl-dll
          path: yasl.dll

  test-python:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Download shared library
        uses: actions/download-artifact@v4
        with:
          name: yasl-so
          path: .
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run Python API tests
        run: |
          cp yasl.so api/python/
          python -m unittest discover -s tests/python
